name: db_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  http: ^0.13.6
  args: ^2.4.1
  dio: ^5.1.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  retrofit_generator: ^7.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0